### ISSUE TITLE
Rework Datepicker widget.

### ISSUE THREAD

**Issue by tjrivera** [chop-dbhi/ehb-datasources#22]
cc: @r3m0chop 

Users are experiencing some issues where the datepicker is auto-filling dates when starting to type into date fields on the REDCap driver.

**Comment by r3m0chop** [comment]
@tjrivera - I imagine that's just a general browser caching auto-fill issue, as the date-picker itself doesn't really do this, but I have a look into it....

**Comment by r3m0chop** [comment]
@tjrivera - Please note that I do not seem to currently have access to any of the RedCap forms through https://brp.research.chop.edu/.  Even on Project: `*TRAINING* UPHS-CHOP Neurosurgery Collaborative Tissue Bank`, I encounter: `Not authorized for this Protocol Data Source`

**Comment by tjrivera** [comment]
cc: @r3m0chop 

A couple updates made to the date picker across 3960e9468057fb7912a1dc5aa7ce12bb5ca0e03f and 91166089fd0f94a2f01db457fbf7766e545558a1. Validation on manual input works the same thanks to your valiDate function. The datepicker is now explicitly activated via an icon next to the input field.

Visually it looks like this:

![screen shot 2016-07-11 at 10 24 18 am](https://cloud.githubusercontent.com/assets/4405800/16733948/acfa8746-4751-11e6-9247-da7d686ef597.png)
