### ISSUE TITLE
No nautilus feedback of expired password

### ISSUE THREAD

**Issue by alexfelmeister** [chop-dbhi/ehb-datasources#29]
![screen shot 2017-06-14 at 11 30 25 am](https://user-images.githubusercontent.com/2599734/27140949-e1c0c19a-50f4-11e7-842f-d36284dfa0b1.png)

**Comment by seg1129** [comment]
When Nautilus password is expired there is not notification through the BRP. The user only sees an empty list of aliquots - see the example screenshot above.

**Comment by seg1129** [comment]
@alexfelmeister, will this error message help?

<img width="930" alt="screen shot 2017-06-20 at 4 57 34 pm" src="https://user-images.githubusercontent.com/18520534/27355628-bbaa0f5e-55d9-11e7-9f95-b36606007d39.png">

**Comment by alexfelmeister** [comment]
Absolutely!  "Unable to communicate with Laboratory System, please contact the data coordinating center or eigsupport@email.chop.edu.

**Comment by alexfelmeister** [comment]
Unable to communicate with Laboratory System because of expired or incorrect credentials. Please contact the data coordinating center or eigsupport@email.chop.edu.

**Comment by seg1129** [comment]
<img width="1155" alt="screen shot 2017-06-23 at 9 46 14 am" src="https://user-images.githubusercontent.com/18520534/27485636-80a680a8-57fb-11e7-96c9-7c0a7c8ffdfe.png">

**Comment by seg1129** [comment]
Tyler - I created a release and updated the BRP wit the version number, however the change is still not reflected in production. Any thoughts as to what I missed?

**Comment by tjrivera** [comment]
@seg1129 there is still no automatic deployment from master to production. You have to manually deploy the latest changes.

**Comment by seg1129** [comment]
@tjrivera I deployed the BRP last night Jenkins run #148

**Comment by tjrivera** [comment]
It looks like your last commit updates the requirements.txt but does not update the dependencies in the [Dockerfile](https://github.com/chop-dbhi/biorepo-portal/blob/master/Dockerfile#L32) It is still using 1.0.4

**Comment by seg1129** [comment]
Ah! Thank you! I knew I was missing something.

**Comment by seg1129** [comment]
This issue is resolved with Datasources version 1.0.5
