### ISSUE TITLE
Data Widget in Redcap datasource not showing correctly

### ISSUE THREAD

**Issue by alexfelmeister** [chop-dbhi/ehb-datasources#34]
Users report the "today" button is missing on the BRP generated REDCap forms. 
<img width="501" alt="screen shot 2017-08-31 at 2 05 42 pm" src="https://user-images.githubusercontent.com/2599734/29939014-8663c684-8e58-11e7-836c-1af2d9502a19.png">

**Comment by alexfelmeister** [comment]
https://app.asana.com/0/29102342672473/424411457026270

**Comment by alexfelmeister** [comment]
Example of other issue mentioned in the asana ticket 
<img width="613" alt="screen shot 2017-10-26 at 6 49 16 pm" src="https://user-images.githubusercontent.com/2599734/32080828-d60e562e-ba7f-11e7-85d1-66919c3647cd.png">

**Comment by r3m0chop** [comment]
I seem to remember Tyler taking the Today button out entirely when upgrading to the React-based BRP-GUI due to incompatibilities, and am not sure if it can find its way back in, at least not as it was.

**Comment by seg1129** [comment]
<img width="659" alt="screen shot 2017-11-02 at 11 02 51 pm" src="https://user-images.githubusercontent.com/18520534/32359167-2dab5a92-c022-11e7-895c-c3141a954d0c.png">
Issue resolved.

**Comment by alexfelmeister** [comment]
👍
